### ISSUE TITLE
Record "last used" date for kernels that were started without the table

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-new-launcher#29]
Currently kernels that are started outside of the extension UI do not get "last used" date updated.
This is in particular problematic if user opens a with an already associated kernel as this makes "last used" column value different than what expected by the user.

We can do better by listening to kernels as they get started via services API, regardless of what started them.

**Comment by krassowski** [comment]
May require a decision on https://github.com/nebari-dev/jupyterlab-new-launcher/issues/2

**Comment by ericdatakelly** [comment]
More testing in case it helps: 
I made a new environment, which I assume creates a new kernel, but still I saw no change to the "last used" value (still shows "Never").  Next I selected "Shut down all kernels", stopped JLab, logged out of Nebari, waited 6 minutes, logged back in and restarted JLab with a different server size (small instead of tiny). "Last used"still showed "Never".

**Comment by krassowski** [comment]
> I made a new environment, which I assume creates a new kernel , but still I saw no change to the "last used" value (still shows "Never")

The definition of "used" is that the kernel was created (i.e. notebook was opened and kernel was started), not that the environment was used. Detecting when an environment was used would be a much harder problem.

**Comment by krassowski** [comment]
I can reproduce a bug in that when the kernel is selected in the pop-up dialog it does not get recorded. The launcher itself is not affected.
