### ISSUE TITLE
Initial UI Review

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/jupyterlab-new-launcher#4]
### Context

Moving the discussion from the [initial design issue](https://github.com/conda-incubator/conda-store-ui/issues/255) over to this repo for the review process. 

<img width="1478" alt="image" src="https://github.com/nebari-dev/jupyterlab-new-launcher/assets/15659110/c00fb8ce-1496-432b-a13d-b87d451e46bc">

UI nitpicks based on design:
* wording from UI doesn't match design (e.g. "Create Empty" should be "Open New by Type" and "Launch Notebook" should be "Open new notebook by kernel")
* Missing header "Launch New Session" at the top of the page
* Move search to Open New By Kernel section because that is where search is most needed. Make the empty field text be "Search for Kernel."
* Starred section is missing

### Value and/or benefit

.

### Anything else?

Original issue: https://github.com/conda-incubator/conda-store-ui/issues/255

**Comment by krassowski** [comment]
I would propose to keep the changes to headings as I did implement the design word for word initially but in my testing it took to much space and the titles were more confusing than helpful. I interpreted that part of the design to be placeholders, but if the choice of wording was deliberate we can do A/B.

The starred section should be optional, based on the discussions from design review, right? Let me add it in behind a setting.

Regarding the filter box position I think this can be configurable too because there is a trade-off: having them on each level will make it take up more space and will prevent filtering all other items. The placeholder text can be then adjusted accordingly.

**Comment by krassowski** [comment]
Should we merge the "Icon" and "Kernel" columns? This would be closer to the design and I think there is not much use from having them separately. The only advantage would be that user could hide "Icon" column altogether but it does not seem very pleasant to work without icons (well maybe if all you have is Python environments only then it is not needed?)

**Comment by kcpevey** [comment]
>Should we merge the "Icon" and "Kernel" columns? 

Yes, I think that's a good idea. I was wondering about the verbosity of "Python [conda env:notebook]". I don't know what the other options are here, but it seems like just "python" is sufficient?

**Comment by krassowski** [comment]
> I don't know what the other options are here, but it seems like just "python" is sufficient?

The format of the kernel display returned by `conda_nb_kernels` is customizable by `CondaKernelSpecManager.name_format` traitlet which goes to `jupyter_server_config.py`, by default `'{language} [conda env:{environment}]'` ([docs](https://github.com/anaconda/nb_conda_kernels?tab=readme-ov-file#configuration)). I think since we will be showing all details in other columns, we can configure it to just `{display_name}`. I am not sure if this is a responsibility of this extension; while technically it could override the server-side settings of other extensions (like conda-nb-kernels), this is a bit rude for users who want to configure it independently. Maybe we should just add a suggestion in readme.

**Comment by krassowski** [comment]
> The format of the kernel display returned by `conda_nb_kernels` is customizable by `CondaKernelSpecManager.name_format` traitlet

Nebari customizes it to `{environment}` [here](https://github.com/nebari-dev/nebari/blob/bb321cf1159a950d58333f2f919242f4324755b6/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L343)

The problem with conda-store's `{environment}` variable is that it includes both the user name (namespace) and the environment name. We can special-case environment column to split it into two based on a known delimiter format.

**Comment by krassowski** [comment]
Testing with nebari, here are some more tasks:
- [ ] VS Code pretends to be a kernel, we need to special-case it to move it to "Create Empty" section
- [ ] I think that "Notebook Jobs" do not belong in "Create Empty" section but in top-right corner with "Contextual Help"

![image](https://github.com/nebari-dev/jupyterlab-new-launcher/assets/5832902/56e434df-3c86-4dcd-a008-b6ba67ab8128)

**Comment by krassowski** [comment]
The idea of splitting on delimiter would only work if it was not allowed in environment nor user names, but currently it is (as the delimiter is just `-`):

![image](https://github.com/nebari-dev/jupyterlab-new-launcher/assets/5832902/8647a546-aa12-4068-91e0-de9b07865001)

**Comment by krassowski** [comment]
> The idea of splitting on delimiter would only work if it was not allowed in environment nor user names, but currently it is (as the delimiter is just -):

Resolved with a simple regex in 68db1635262d38b67a3406cd12e2a8dc4a783033.

**Comment by kcpevey** [comment]
>Do you know if it is possible to deploy a conda-store with a few pre-defined environments to binder?

I dont think its possible to deploy conda-store itself to binder, but I also don't know if its possible to deploy just multiple conda environments to binder. 

>Resolved with a simple regex in https://github.com/nebari-dev/jupyterlab-new-launcher/commit/68db1635262d38b67a3406cd12e2a8dc4a783033.

nice!

**Comment by kcpevey** [comment]
@krassowski should we close this issue and open more targeted issues going forward?

**Comment by krassowski** [comment]
Yes, let's do that!
